### ISSUE TITLE
Pop Up Attack + Boom + "You Have Been Hacked" 

### ISSUE THREAD

**Issue by julia-meyr** [SYP-AHIF-2023-24-25/CubeIT#22]

**Comment by amina-gbc** [comment]
1. Pop Up Attack --> Commandlines (grün oder rot) --> Der DeepSpace wird gehackt (Der Virus wird installiert)
2. Boom --> Knock-Out (Der gesamte DeepSpace wird schwarz)
3. "You Have Been Hacked" --> Message (Der gesamte DeepSpace wird rot)
